trigger:
  - new-pipeline-test
parameters:
  - name: runtaskcode
    type: boolean
    default: false
    displayName: "run build stage"
  - name: runtaskdev
    type: boolean
    default: false
    displayName: "run development deployment"
  - name: runtasktqa
    type: boolean
    default: false
    displayName: "run qa deployment"
  - name: runtaskprod
    type: boolean
    default: false
    displayName: "run production deployment"

variables:
  - name: variable-parametro
    value: ${{ parameters.runtaskdev}}


stages:
  - stage: "Build"
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: "Download_Code"
        steps:
          - task: CmdLine@2
            inputs:
              script: | 
                echo Write your commands here
                echo Hello world
  - stage: "DEV"
    dependsOn: [Build]
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: "Deploy_Dev"
        steps:
          - checkout: self
          - script: echo "Deploying to DEV"
            displayName: 'Deploying to DEV'
            condition: and(succeeded(), eq(${{parameters.runtaskdev}}, 'true'))
